"""empty message

Revision ID: 508f0088f843
Revises: 
Create Date: 2020-02-15 21:05:57.588488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508f0088f843'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('incident_report_for', sa.String(), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(), nullable=False),
    sa.Column('incident_reported_by', sa.String(), nullable=False),
    sa.Column('report_datetime', sa.DateTime(), nullable=False),
    sa.Column('fixed_on', sa.DateTime(), nullable=False),
    sa.Column('outage_duration', sa.DateTime(), nullable=False),
    sa.Column('outage_severity', sa.String(), nullable=False),
    sa.Column('sre_on_call', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('root_cause_analysis', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('bugs', sa.Text(), nullable=True),
    sa.Column('recovery', sa.Text(), nullable=False),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('closing_remarks', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rca')
    # ### end Alembic commands ###
